# Generated by Django 4.2.11 on 2024-04-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
