# Generated by Django 4.2.11 on 2024-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_purchaseorder_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="PO Number"
            ),
        ),
    ]
