# Generated by Django 4.2.11 on 2024-04-29 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_purchaseorder_po_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "ordering": ("-created",),
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
